spring:
  kafka:
    listener:
      ack-mode: record
    bootstrap-servers: 192.168.14.200:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: newMock